version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "10:00"
    timezone: Etc/UCT
  reviewers:
  - RandomByte
  - matz3
  versioning-strategy: increase
  ignore:
  - dependency-name: ava
    versions:
    - "< 1.0.2"
    - ">= 1.0.1.a"
  - dependency-name: pacote
    versions:
    - ">= 10.a"
    - "< 11"
  - dependency-name: pacote
    versions:
    - ">= 11.a"
    - "< 12"
