const {promisify} = require("util");
const rimraf = promisify(require("rimraf"));
const resourceFactory = require("@ui5/fs").resourceFactory;
const log = require("@ui5/logger").getGroupLogger("builder");
const BuildContext = require("./buildHelpers/BuildContext");
const composeProjectList = require("./buildHelpers/composeProjectList");
const getBuildDefinitionInstance = require("./buildDefinitions/getInstance");

async function executeCleanupTasks(buildContext) {
	log.info("Executing cleanup tasks...");
	await buildContext.executeCleanupTasks();
}

function registerCleanupSigHooks(buildContext) {
	function createListener(exitCode) {
		return function() {
			// Asynchronously cleanup resources, then exit
			executeCleanupTasks(buildContext).then(() => {
				process.exit(exitCode);
			});
		};
	}

	const processSignals = {
		"SIGHUP": createListener(128 + 1),
		"SIGINT": createListener(128 + 2),
		"SIGTERM": createListener(128 + 15),
		"SIGBREAK": createListener(128 + 21)
	};

	for (const signal of Object.keys(processSignals)) {
		process.on(signal, processSignals[signal]);
	}

	// == TO BE DISCUSSED: Also cleanup for unhandled rejections and exceptions?
	// Add additional events like signals since they are registered on the process
	//	event emitter in a similar fashion
	// processSignals["unhandledRejection"] = createListener(1);
	// process.once("unhandledRejection", processSignals["unhandledRejection"]);
	// processSignals["uncaughtException"] = function(err, origin) {
	// 	const fs = require("fs");
	// 	fs.writeSync(
	// 		process.stderr.fd,
	// 		`Caught exception: ${err}\n` +
	// 		`Exception origin: ${origin}`
	// 	);
	// 	createListener(1)();
	// };
	// process.once("uncaughtException", processSignals["uncaughtException"]);

	return processSignals;
}

function deregisterCleanupSigHooks(signals) {
	for (const signal of Object.keys(signals)) {
		process.removeListener(signal, signals[signal]);
	}
}

/**
 * Calculates the elapsed build time and returns a prettified output
 *
 * @private
 * @param {Array} startTime Array provided by <code>process.hrtime()</code>
 * @returns {string} Difference between now and the provided time array as formatted string
 */
function getElapsedTime(startTime) {
	const prettyHrtime = require("pretty-hrtime");
	const timeDiff = process.hrtime(startTime);
	return prettyHrtime(timeDiff);
}

/**
 * Configures the project build and starts it.
 *
 * @public
 * @param {object} parameters Parameters
 * @param {module:@ui5/project.graph.ProjectGraph} parameters.graph Project graph as generated by the
 * 									[@ui5/project.normalizer]{@link module:@ui5/project.normalizer}
 * @param {string} parameters.destPath Target path
 * @param {boolean} [parameters.cleanDest=false] Decides whether project should clean the target path before build
 * @param {Array.<string|RegExp>} [parameters.includedDependencies=[]]
 *			List of names of projects to include in the build result
 *			If the wildcard '*' is provided, all dependencies will be included in the build result.
 * @param {Array.<string|RegExp>} [parameters.excludedDependencies=[]]
 *			List of names of projects to exclude from the build result.
 * @param {object} [parameters.complexDependencyIncludes] TODO 3.0
 * @param {boolean} [parameters.selfContained=false] Flag to activate self contained build
 * @param {boolean} [parameters.cssVariables=false] Flag to activate CSS variables generation
 * @param {boolean} [parameters.jsdoc=false] Flag to activate JSDoc build
 * @param {Array.<string>} [parameters.includedTasks=[]] List of tasks to be included
 * @param {Array.<string>} [parameters.excludedTasks=[]] List of tasks to be excluded.
 * 							If the wildcard '*' is provided, only the included tasks will be executed.
 * @returns {Promise} Promise resolving to <code>undefined</code> once build has finished
 */
module.exports = async function({
	graph, destPath, cleanDest = false,
	includedDependencies = [], excludedDependencies = [],
	complexDependencyIncludes,
	selfContained = false, cssVariables = false, jsdoc = false,
	includedTasks = [], excludedTasks = [],
}) {
	if (graph.isSealed()) {
		throw new Error(
			`Can not build project graph with root node ${this._rootProjectName}: Graph has already been sealed`);
	}

	if (complexDependencyIncludes) {
		if (includedDependencies.length || excludedDependencies.length) {
			throw new Error(
				"Parameter 'complexDependencyIncludes' can't be used in conjunction " +
				"with parameters 'includedDependencies' or 'excludedDependencies");
		}
		const deps = await composeProjectList(graph, complexDependencyIncludes);
		includedDependencies = deps.includedDependencies;
		excludedDependencies = deps.excludedDependencies;
	}

	const startTime = process.hrtime();
	const rootProjectName = graph.getRoot().getName();
	log.info(`Starting build of project ${rootProjectName}...`);
	log.info(`  Target directory: ${destPath}`);
	log.info(`  Including dependencies: ${includedDependencies.join(", ")}`);
	log.info(`  Excluding dependencies: ${excludedDependencies.join(", ")}`);

	const buildParams = {selfContained, jsdoc, includedTasks, excludedTasks};

	const fsTarget = resourceFactory.createAdapter({
		fsBasePath: destPath,
		virBasePath: "/"
	});

	const buildContext = new BuildContext({
		graph,
		options: {
			cssVariables: cssVariables
		}
	});
	const cleanupSigHooks = registerCleanupSigHooks(buildContext);
	function projectFilter(projectName) {
		function projectMatchesAny(deps) {
			return deps.some((dep) => dep instanceof RegExp ?
				dep.test(projectName) : dep === projectName);
		}

		if (projectName === rootProjectName) {
			// Always include the root project
			return true;
		}

		// if everything is included, this overrules exclude lists
		if (includedDependencies.includes("*")) return true;
		let test = false;

		if (test && projectMatchesAny(excludedDependencies)) {
			test = false;
		}
		if (!test && projectMatchesAny(includedDependencies)) {
			test = true;
		}

		return test;
	}

	// Count total number of projects to build
	const projectsToBuild = graph.getAllProjects().map((arr) => arr[0]).filter(function(projectName) {
		return projectFilter(projectName);
	});

	const buildLogger = log.createTaskLogger("🛠 ", projectsToBuild.length);
	log.info(`Building projects: `);
	log.info(`    > ${projectsToBuild.join("\n    > ")}`);
	try {
		if (cleanDest) {
			await rimraf(destPath);
		}

		await graph.traverseDepthFirst(async function({project, getDependencies}) {
			if (!projectsToBuild.includes(project.getName())) {
				return;
			}
			const projectContext = buildContext.createProjectContext({
				project,
				log: buildLogger
			});
			buildLogger.startWork(`Building project ${project.getName()}...`);

			const readers = [];
			await graph.traverseBreadthFirst(project.getName(), async function({project: dep}) {
				if (dep.getName() === project.getName()) {
					return;
				}
				readers.push(dep.getReader({
					includeTestResources: true
				}));
			});

			const dependencies = resourceFactory.createReaderCollection({
				name: `Dependency reader collection for project ${project.getName()}`,
				readers
			});

			const taskUtil = projectContext.getTaskUtil();
			const builder = getBuildDefinitionInstance({
				graph,
				project,
				taskUtil: projectContext.getTaskUtil(),
				parentLogger: log,
				resourceCollections: {
					workspace: project.getWorkspace(),
					dependencies,
				}
			});
			await builder.build(buildParams);
			log.verbose("Finished building project %s. Writing out files...", project.getName());
			buildLogger.completeWork(1);

			const resources = await project.getReader({style: "runtime"}).byGlob("/**/*");

			await Promise.all(resources.map((resource) => {
				if (taskUtil.getTag(resource, taskUtil.STANDARD_TAGS.OmitFromBuildResult)) {
					log.verbose(`Skipping write of resource tagged as "OmitFromBuildResult": ` +
						resource.getPath());
					return; // Skip target write for this resource
				}
				return fsTarget.write(resource);
			}));
		});
		log.info(`Build succeeded in ${getElapsedTime(startTime)}`);
	} catch (err) {
		log.error(`Build failed in ${getElapsedTime(startTime)}`);
		throw err;
	} finally {
		deregisterCleanupSigHooks(cleanupSigHooks);
		await executeCleanupTasks(buildContext);
	}
};
